# Clippy configuration for backend linting
msrv = "1.70"

# Allow some common patterns
avoid-breaking-exported-api = false

# Enable additional lints
pedantic = true
nursery = false

# Disable overly strict lints for this codebase
disallowed-methods = []
disallowed-types = []
disallowed-macros = []

# Allow certain patterns common in web services
allow = [
    "clippy::module_name_repetitions",
    "clippy::too_many_lines",
    "clippy::missing_errors_doc",
    "clippy::missing_panics_doc"
]
