# Clippy configuration for backend linting
msrv = "1.70"

# Allow some common patterns
avoid-breaking-exported-api = false

# Disable overly strict lints for this codebase
disallowed-methods = []
disallowed-types = []
disallowed-macros = []

# Threshold configurations
too-many-lines-threshold = 150
cognitive-complexity-threshold = 30
type-complexity-threshold = 250
