name: 'Backend CI/CD Pipeline'

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

env:
  RUST_VERSION: '1.80'
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true
  
jobs:
  pre-checks:
    name: 'Pre-flight Checks'
    runs-on: ubuntu-latest
    outputs:
      should-deploy: ${{ steps.check-branch.outputs.should-deploy }}
      git-sha: ${{ steps.vars.outputs.git-sha }}
      timestamp: ${{ steps.vars.outputs.timestamp }}
    steps:
      - name: '[INFO] : Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: '[INFO] : Set pipeline variables'
        id: vars
        run: |
          echo "[INFO] : Setting pipeline variables"
          echo "git-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "timestamp=$(date -u +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
          echo "[INFO] : Git SHA: $(git rev-parse --short HEAD)"
          echo "[INFO] : Timestamp: $(date -u +%Y%m%d-%H%M%S)"

      - name: '[INFO] : Check deployment eligibility'
        id: check-branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "[INFO] : Branch eligible for deployment"
            echo "should-deploy=true" >> $GITHUB_OUTPUT
          else
            echo "[INFO] : Branch not eligible for deployment"
            echo "should-deploy=false" >> $GITHUB_OUTPUT
          fi

  code-quality:
    name: 'Code Quality & Security'
    runs-on: ubuntu-latest
    needs: pre-checks
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: '[INFO] : Checkout repository'
        uses: actions/checkout@v4

      - name: '[INFO] : Setup Rust toolchain'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy

      - name: '[INFO] : Setup Rust cache'
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: '[INFO] : Check code formatting'
        run: |
          echo "[INFO] : Checking Rust code formatting"
          if ! cargo fmt --all -- --check; then
            echo "[ERROR] : Code formatting check failed"
            echo "[ERROR] : Run 'cargo fmt' to fix formatting issues"
            exit 1
          fi
          echo "[INFO] : Code formatting is correct"

      - name: '[INFO] : Run Clippy linting'
        run: |
          echo "[INFO] : Running Clippy linting"
          if ! cargo clippy --all-targets --all-features -- -D warnings; then
            echo "[ERROR] : Clippy linting failed"
            exit 1
          fi
          echo "[INFO] : Clippy linting passed"

      - name: '[INFO] : Security audit'
        run: |
          echo "[INFO] : Running security audit"
          cargo install --quiet cargo-audit || echo "[WARN] : Failed to install cargo-audit"
          if command -v cargo-audit >/dev/null 2>&1; then
            if ! cargo audit; then
              echo "[WARN] : Security vulnerabilities found"
            else
              echo "[INFO] : No security vulnerabilities found"
            fi
          else
            echo "[WARN] : cargo-audit not available, skipping security scan"
          fi

  build-test:
    name: 'Build & Test'
    runs-on: ubuntu-latest
    needs: [pre-checks, code-quality]
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: '[INFO] : Checkout repository'
        uses: actions/checkout@v4

      - name: '[INFO] : Setup Rust toolchain'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: '[INFO] : Setup Rust cache'
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: '[INFO] : Install sqlx-cli'
        run: |
          echo "[INFO] : Installing sqlx-cli for database operations"
          cargo install --quiet sqlx-cli --no-default-features --features native-tls,postgres

      - name: '[INFO] : Setup test database'
        env:
          DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
        run: |
          echo "[INFO] : Setting up test database"
          if ! sqlx database create; then
            echo "[ERROR] : Failed to create test database"
            exit 1
          fi
          
          if ! sqlx migrate run; then
            echo "[ERROR] : Failed to run database migrations"
            exit 1
          fi
          echo "[INFO] : Database setup completed"

      - name: '[INFO] : Run tests'
        env:
          DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
          RUST_LOG: debug
        run: |
          echo "[INFO] : Running unit and integration tests"
          if ! cargo test --verbose --all-features; then
            echo "[ERROR] : Tests failed"
            exit 1
          fi
          echo "[INFO] : All tests passed"

      - name: '[INFO] : Build release binary'
        run: |
          echo "[INFO] : Building optimized release binary"
          if ! cargo build --release --verbose; then
            echo "[ERROR] : Release build failed"
            exit 1
          fi
          echo "[INFO] : Release build completed successfully"
          
          # Check binary size and basic info
          ls -lh target/release/kizo-server || echo "[WARN] : Binary not found at expected location"

      - name: '[INFO] : Upload build artifacts'
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-${{ needs.pre-checks.outputs.git-sha }}
          path: |
            target/release/kizo-server
            Cargo.toml
            Cargo.lock
          retention-days: 7

  docker-build:
    name: 'Docker Build & Scan'
    runs-on: ubuntu-latest
    needs: [pre-checks, build-test]
    if: needs.pre-checks.outputs.should-deploy == 'true'
    steps:
      - name: '[INFO] : Checkout repository'
        uses: actions/checkout@v4

      - name: '[INFO] : Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: '[INFO] : Build Docker image'
        run: |
          echo "[INFO] : Building Docker image"
          IMAGE_TAG="kizo-backend:${{ needs.pre-checks.outputs.git-sha }}"
          if ! docker build -t $IMAGE_TAG -f Dockerfile .; then
            echo "[ERROR] : Docker build failed"
            exit 1
          fi
          echo "[INFO] : Docker image built: $IMAGE_TAG"
          
          # Save image info
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: '[INFO] : Scan Docker image for vulnerabilities'
        run: |
          echo "[INFO] : Scanning Docker image for security vulnerabilities"
          # Install Trivy
          sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install -y trivy
          
          # Run security scan
          if trivy image --severity HIGH,CRITICAL --exit-code 1 ${{ env.IMAGE_TAG }}; then
            echo "[INFO] : No critical vulnerabilities found"
          else
            echo "[WARN] : Critical vulnerabilities found in Docker image"
          fi

  deploy:
    name: 'Deploy to Production'
    runs-on: ubuntu-latest
    needs: [pre-checks, docker-build]
    if: needs.pre-checks.outputs.should-deploy == 'true'
    environment:
      name: production
      url: 'https://your-backend-domain.com'
    steps:
      - name: '[INFO] : Checkout repository'
        uses: actions/checkout@v4

      - name: '[INFO] : Validate deployment secrets'
        run: |
          echo "[INFO] : Validating required secrets"
          if [[ -z "${{ secrets.VPS_HOST }}" ]]; then
            echo "[FATAL] : VPS_HOST secret is missing"
            exit 1
          fi
          if [[ -z "${{ secrets.VPS_USERNAME }}" ]]; then
            echo "[FATAL] : VPS_USERNAME secret is missing"
            exit 1
          fi
          if [[ -z "${{ secrets.VPS_SSH_KEY }}" ]]; then
            echo "[FATAL] : VPS_SSH_KEY secret is missing"
            exit 1
          fi
          echo "[INFO] : All required secrets are present"

      - name: '[INFO] : Deploy to VPS'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          command_timeout: 20m
          script: |
            set -e
            
            echo "[INFO] : Starting backend deployment process"
            echo "[INFO] : Git SHA: ${{ needs.pre-checks.outputs.git-sha }}"
            echo "[INFO] : Timestamp: ${{ needs.pre-checks.outputs.timestamp }}"
            
            # Navigate to project directory
            cd /home/kizovps/kizo/backend || {
              echo "[FATAL] : Cannot access backend directory"
              exit 1
            }
            
            # Pull latest changes
            echo "[INFO] : Pulling latest changes from repository"
            if ! git fetch origin; then
              echo "[ERROR] : Failed to fetch from origin"
              exit 1
            fi
            
            if ! git reset --hard origin/master; then
              echo "[ERROR] : Failed to reset to origin/master"
              exit 1
            fi
            
            echo "[INFO] : Repository updated successfully"
            
            # Check if .env exists
            if [[ ! -f "/home/kizovps/kizo/.env" ]]; then
              echo "[WARN] : Main .env file not found, deployment may fail"
            fi
            
            # Build Docker image
            echo "[INFO] : Building backend Docker image"
            IMAGE_TAG="kizo-backend:${{ needs.pre-checks.outputs.git-sha }}"
            if ! sudo docker build -t kizo-backend:latest -t "$IMAGE_TAG" .; then
              echo "[ERROR] : Docker build failed"
              exit 1
            fi
            
            # Stop and remove old container
            echo "[INFO] : Stopping existing backend container"
            sudo docker stop kizo-backend 2>/dev/null || echo "[INFO] : No existing container to stop"
            sudo docker rm kizo-backend 2>/dev/null || echo "[INFO] : No existing container to remove"
            
            # Start new container
            echo "[INFO] : Starting new backend container"
            if ! sudo docker run -d \
              --name kizo-backend \
              --network host \
              --restart unless-stopped \
              --env-file /home/kizovps/kizo/.env \
              --label "git-sha=${{ needs.pre-checks.outputs.git-sha }}" \
              --label "deployed-at=${{ needs.pre-checks.outputs.timestamp }}" \
              kizo-backend:latest; then
              echo "[ERROR] : Failed to start container"
              sudo docker logs kizo-backend --tail 50 2>/dev/null || echo "[ERROR] : Cannot retrieve container logs"
              exit 1
            fi
            
            # Verify deployment
            echo "[INFO] : Verifying backend deployment"
            sleep 15
            
            if sudo docker ps --filter "name=kizo-backend" --filter "status=running" | grep -q kizo-backend; then
              echo "[INFO] : Backend container is running successfully"
              sudo docker logs kizo-backend --tail 20
              
              # Basic health check
              echo "[INFO] : Performing basic health check"
              sleep 5
              if sudo docker exec kizo-backend ps aux | grep -q kizo-server; then
                echo "[INFO] : Backend process is running inside container"
              else
                echo "[WARN] : Backend process may not be running properly"
              fi
            else
              echo "[ERROR] : Backend container failed to start properly"
              sudo docker logs kizo-backend --tail 50 2>/dev/null || echo "[ERROR] : Cannot retrieve logs"
              exit 1
            fi
            
            # Cleanup old images
            echo "[INFO] : Cleaning up old Docker images"
            sudo docker image prune -f
            
            echo "[INFO] : Backend deployment completed successfully"
            echo "[INFO] : Deployment SHA: ${{ needs.pre-checks.outputs.git-sha }}"

      - name: '[INFO] : Post-deployment verification'
        run: |
          echo "[INFO] : Deployment completed"
          echo "[INFO] : Git SHA: ${{ needs.pre-checks.outputs.git-sha }}"
          echo "[INFO] : Deployed at: ${{ needs.pre-checks.outputs.timestamp }}"

  cleanup:
    name: 'Cleanup'
    runs-on: ubuntu-latest
    needs: [pre-checks, deploy]
    if: always()
    steps:
      - name: '[INFO] : Pipeline cleanup'
        run: |
          echo "[INFO] : Backend pipeline execution completed"
          echo "[INFO] : Status: ${{ needs.deploy.result }}"
          if [[ "${{ needs.deploy.result }}" == "failure" ]]; then
            echo "[ERROR] : Backend deployment failed - check logs above"
            exit 1
          fi
          echo "[INFO] : All backend pipeline steps completed successfully"
