name: Deploy Backend

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /home/kizovps/kizo/backend
          
          echo "🔄 Pulling latest changes..."
          git pull origin main || git pull origin master
          
          echo "🦀 Building backend Docker image..."
          sudo docker build -t kizo-backend:latest .
          
          echo "🔄 Stopping old container..."
          sudo docker stop kizo-backend || true
          sudo docker rm kizo-backend || true
          
          echo "🚀 Starting new container..."
          sudo docker run -d \
            --name kizo-backend \
            --network host \
            --restart unless-stopped \
            --env-file /home/kizovps/kizo/.env \
            kizo-backend:latest
          
          echo "🧹 Cleaning up old images..."
          sudo docker image prune -f
          
          echo "✅ Backend deployment completed!"
          sudo docker ps | grep kizo-backend
